### ISSUE TITLE
Degree Elevation

### ISSUE THREAD

**Issue by tawfikkhaled** [orbingol/NURBS-Python#12]

**Comment by orbingol** [comment]
From what I understand from the description text in this issue is that this repository urgently needs a Code of Conduct document. I will take care of it this weekend.

Degree Elevation? Well, I would love to see OP's contributions on degree elevation implementation on the **surfaces**. That means I need to take care of the Contributing document too. Consider it done with the Code of Conduct. So, what about the curves? Anyone can do the curves, even I can do it :) It is easy, so maybe you can consider contributing the degree elevation implementation on curves while you are working on the surfaces.
