### ISSUE TITLE
Join in the NURBS workbench for Freecad

### ISSUE THREAD

**Issue by FraJoMen** [orbingol/NURBS-Python#13]
Hi ! fist of all congratulation for your work, I star to study your cod and The NURBS Book ! What do you think about to implement your cod in the Silk project?. Silk (https://edwardvmills.github.io/Silk/) have the vantage from GUI and Freecad tool.

I wish do a code to make  Isogeometric Analysis (IGA) and will be amazing work together. IGA  employs NURBS  for integrate Partial Differential Equation. The plan is:

1) Advantage from a GUI in Silk workbench for Freecad (https://forum.freecadweb.org/viewtopic.php?f=22&t=23243)
2) Implement your function for build a grate model NURBS code, I'm working for performs a boolean operations on solids represented by NURBS
3) Develop a PDE Solver (something like this http://rafavzqz.github.io/geopdes/)

**Comment by orbingol** [comment]
Thanks @FraJoMen, I appreciate it. I am glad you liked this library.

I have been so far away from this code because of my responsibilities with the other projects. I am planning to return back, test the latest changes and push them very soon, hopefully. The next steps for this library are knot and degree operations (knot insertion, knot removal, etc) and these will be implemented in this package, probably till the end of this year.

Unfortunately, I am not a user of FreeCAD or Silk. I know that there are a lot of researchers and companies working on solid and geometric modeling and they are doing great job. I appreciate their work and most of the time I use their work in my research too.

If you would like to, you can use this python package in your work. This is a free and open-source software released on a public domain under MIT License and this is the only restriction. I would prefer you to use my work as a git submodule, which you would find very easy to maintain in case of any problems. I would also be glad if you use the supplied DOI number to cite my work, if you use it in an academic research.

Please let me know if you have any other questions or comments.
