### ISSUE TITLE
[Suggesion] The Axes3D is not an appropriate way to create the 3D axis handle

### ISSUE THREAD

**Issue by jerryliu20d** [orbingol/NURBS-Python#159]
I cannot correctly visualize the 3d plots via Geomdl functions (matplotlib 3.6.2). l I notice that in the visualization functions, NURBS-Python uses `ax = Axes3D(fig)` to initiate the 3D axis handle. According to the issue in Matplotlib here: https://github.com/matplotlib/matplotlib/issues/24639 , it is recommended to use `ax = fig.add_subplot(projection='3d')` instead. Thanks!

**Comment by orbingol** [comment]
This is not fixable due to the reasons explained in another ticket (https://github.com/orbingol/NURBS-Python/issues/161#issuecomment-1373123879). Matplotlib changed its API interface a while ago after a major update. Please use an older version of Matplotlib, I'd suggest using `v3.4.0` for the moment. Sorry for the inconvenience.

The new major release of geomdl will address such issues in a more modular way, but there will be an API change between `v5` and the next version.
