### ISSUE TITLE
VTK renders are very noisy compared to MPL renders

### ISSUE THREAD

**Issue by abhishekpandey07** [orbingol/NURBS-Python#41]
**Describe the bug**
The VisVTK Visualisation module renders partly deformed surfaces. VisMPL module works as expected.

**To Reproduce**
1. fit a point cloud.
2. set delta to 0.02
3. render using VTK

**Expected Behavior**
The VisVTK module should render the surfaces as they are.

**Configuration:**
 - OS: Ubuntu 18.10
 - Python distribution: Anaconda
 - Python version: 3.6.8
 - geomdl install source: Anaconda
 - geomdl version/branch: 5.0b4

**Screenshots (Optional)**
![mesh2_mpl](https://user-images.githubusercontent.com/29663447/51731832-1315c600-2074-11e9-909c-c6c4a0d267d6.png)
![mesh2_vtk](https://user-images.githubusercontent.com/29663447/51731834-14df8980-2074-11e9-8a65-c719d949b1c5.png)
![mpl](https://user-images.githubusercontent.com/29663447/51731836-16a94d00-2074-11e9-8248-aac774c92e88.png)
![vtk](https://user-images.githubusercontent.com/29663447/51731839-190ba700-2074-11e9-8a47-11d075658c13.png)

**Comment by orbingol** [comment]
The reason for this problem is that geomdl MPL renderer uses a custom tessellation algorithm instead of Matplotlib's integrated QHull library but geomdl  VTK renderer uses the default Delaunay triangulation filters which come with the VTK library itself. It is also possible to observe a similar error when a cylindrical or a conical surface is rendered.

Actually, I wouldn't consider this issue as a bug of geomdl but maybe an integration problem related to how different renderers work. I was able to solve it by using a custom tessellator for Matplotlib. If there is a way to feed pre-generated triangles to VTK system (definitely without using their Delaunay triangulation filter), then I guess, that would be the solution.

**Comment by abhishekpandey07** [comment]
Alright, Thanks for making that clear.

**Comment by orbingol** [comment]
I've pushed a fix on `devmaster` branch and tested with a couple of multi-surface objects. It seems to work fine.

**Comment by orbingol** [comment]
This issue is fixed with the release of geomdl v5.2.0
