### ISSUE TITLE
hohoho!!!

### ISSUE THREAD

**Issue by nortikin** [orbingol/NURBS-Python#6]
Great i found you.
Sverchok must have it onboard
:no_good_man: :ok_man: 😍 😆 :ru: 
![levels 19](https://cloud.githubusercontent.com/assets/5783432/25908940/4cd4bc90-35b4-11e7-9aaf-ca7ebf543217.png)
![levels 18](https://cloud.githubusercontent.com/assets/5783432/25908938/4cd4bae2-35b4-11e7-88af-1147df0dbe57.png)
![levels 17](https://cloud.githubusercontent.com/assets/5783432/25908941/4cd5ebf6-35b4-11e7-8403-9df8242b6b98.png)
![levels 16](https://cloud.githubusercontent.com/assets/5783432/25908943/4cd7b9e0-35b4-11e7-8b6d-693b1b16b5d6.png)
![levels 15](https://cloud.githubusercontent.com/assets/5783432/25908942/4cd5fa1a-35b4-11e7-988d-8d813168d127.png)
![levels 14](https://cloud.githubusercontent.com/assets/5783432/25908939/4cd4d39c-35b4-11e7-9ebc-3a80b1c91905.png)
![levels 13](https://cloud.githubusercontent.com/assets/5783432/25908945/4cee158c-35b4-11e7-82aa-82dcd5f5d2fd.png)
![levels 12](https://cloud.githubusercontent.com/assets/5783432/25908946/4cef63d8-35b4-11e7-81d7-d5ce5dbb02e2.png)
![levels 11](https://cloud.githubusercontent.com/assets/5783432/25908947/4cefb234-35b4-11e7-9ad8-2cfe9b7a943d.png)
![levels 10](https://cloud.githubusercontent.com/assets/5783432/25908950/4cf68424-35b4-11e7-8046-891aec86563b.png)
![levels 9](https://cloud.githubusercontent.com/assets/5783432/25908949/4cf2129a-35b4-11e7-954d-62c67f2c3f5b.png)
![levels 8](https://cloud.githubusercontent.com/assets/5783432/25908948/4cf13eec-35b4-11e7-80be-bf7ff78b2da1.png)
![levels 7](https://cloud.githubusercontent.com/assets/5783432/25908951/4d07f696-35b4-11e7-879d-3a4bc37399e1.png)
![levels 6](https://cloud.githubusercontent.com/assets/5783432/25908952/4d09d9ca-35b4-11e7-93db-9b4bbdc828e5.png)
![levels 5](https://cloud.githubusercontent.com/assets/5783432/25908953/4d0b4e22-35b4-11e7-898a-1d6360ed8fcb.png)
![levels 4](https://cloud.githubusercontent.com/assets/5783432/25908955/4d116ca8-35b4-11e7-9474-b5311d503bde.png)
![levels 3](https://cloud.githubusercontent.com/assets/5783432/25908956/4d151ed4-35b4-11e7-95be-29490e3ae133.png)
![levels 2](https://cloud.githubusercontent.com/assets/5783432/25908954/4d0fa83c-35b4-11e7-9b2f-2508cb418e26.png)

**Comment by orbingol** [comment]
@nortikin I wish I could understand what you mean, especially with that title "hohoho!!!". Are you trying to be funny or what?

**Comment by nortikin** [comment]
i'm happy to find your repo.
Newermind. Thank you for your work

**Comment by nortikin** [comment]
sorry, Sverchok is http://github.com/nortikin/sverchok

**Comment by orbingol** [comment]
@nortikin You could have told these directly (or, maybe, emailed me) with a more relevant title and descriptive figures. I thought that somebody was spamming the issue tracker, which is always possible as this project is on a public domain and freely accessible. But, I got your point. Thank you for your messages and nice figures :)

I really appreciate and also respect other people's work on computer graphics, as I believe that all of these works are results of incredible amount of time and effort. I take every issue and every comment on Github very seriously and I try to make everything right as much as possible. I also receive emails on some issues, and subsequently fix them (or rewrite the code causing the issue). I really appreciate people testing and using my code for their own research or other purposes.

Thanks again for your time.

**Comment by nortikin** [comment]
can this tool be in numpy? or don't you know who maybe made numpy version?

**Comment by orbingol** [comment]
@nortikin I would answer your first question as yes, but no :)

Well, actually it is impossible to underestimate the advantages of numpy package in programming mathematical tools, but I believe that people use numpy a lot even it is unnecessary to use in some development environments. It would be very advantageous to use numpy in this NURBS package, but I believe that if I could do it with minimum dependencies, I should do it like that.

However, I think you might want to ask for a feature which returns a numpy array instead of a 2D native list structure. That is something doable but it should be optional, so that people who are not using numpy package can use this NURBS package too. Not everyone is using the well-known Python distributions (including me) and in some development environments, it might be impossible to install/compile some of the dependencies (I have seen some).

I am very open to developing new features that people can advantage of. If you could open **a new feature request** with all possible details (and with some reasons on why we should add it to this package), I would try to implement as soon as possible.

**Comment by nortikin** [comment]
thank you.
